#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
#    herbstclient "$@"
	cmds="$cmds , $@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn xfce4-terminal
# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-j     focus left
hc keybind $Mod-k     focus down
hc keybind $Mod-l     focus up
hc keybind $Mod-semicolon     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split   bottom  0.5
hc keybind $Mod-h       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-j       resize left +$resizestep
hc keybind $Mod-Control-k       resize down +$resizestep
hc keybind $Mod-Control-l       resize up +$resizestep
hc keybind $Mod-Control-semicolon       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#333333'
hc set frame_bg_active_color '#d64937'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 0

hc attr theme.active.color '#d64937'
hc attr theme.normal.color '#333333'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color '#333333'
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#516d7b'
hc attr theme.active.outer_color '#5a7b8c'
hc attr theme.background_color '#5a7b8c'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1 
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

#custom stuff
xrandr --newmode "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
xrandr --addmode eDP1 1920x1080_60.00
xrandr --output eDP1 --mode 1920x1080_60.00
setxkbmap "us,ru" ",winkeys" "grp:alt_shift_toggle"
hc detect_monitors
xset -b
herbstclient pad 0 22
feh --no-fehbg --bg-fill ~/.bg.jpg
xrdb ~/.Xresources
#no need for checks as you can't run two of anyway
dunst &
mpd &
volnoti &
conky &
clipster -d &
hc keybind $Mod-c spawn clipster -sc
touchscreen=$(xinput list | grep 'ELAN Touchscreen' | awk 'match($0, /id=/){print substr($0, RSTART+3, RLENGTH-1)}')
hc keybind $Mod-q spawn chromium --touch-devices=$touchscreen
hc keybind $Mod-Control-q spawn chromium --touch-devices=$touchscreen --kiosk
hc keybind Mod1+Up spawn amixer -c 1 set Master 1%+
hc keybind Mod1+Down spawn amixer -c 1 set Master 1%-
hc keybind Mod1+Left spawn mpc prev
hc keybind Mod1+Right spawn mpc next
hc keybind Mod1+space spawn mpc toggle
hc keybind $Mod-g spawn ~/.config/herbstluftwm/gaps.sh
#hc keybind $Mod-d spawn dmenu_run -nb "#222222" -sb "#345f0c" -fn "-xos4-terminus-medium-r-*-*-14-*"
#hc keybind $Mod-d spawn ~/.config/herbstluftwm/rofi.sh
hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-o spawn onboard
herbstclient chain $cmds&
#if [[ ! $(pgrep redshift) -gt 1 ]]; then
#redshift -l 56.25:43.94
#fi
#if [[ ! $(pgrep xbindkeys) -gt 1 ]]; then
#xbindkeys
#fi
if [[ ! $(pgrep compton) -gt 1 ]]; then
    compton &
fi
{
    pids=( )
    xfce4-panel -d --sm-client-disable &
    pids+=( $! )
    herbstclient -w '(quit_panel|reload)'
    kill ${pids[@]}
} &
